theme: jekyll-theme-minimal
title: Brian Oyollo
logo: /assets/headshot.png
description: Data Engineer / Backend Developer \n [`Download CV`](https://docs.google.com/document/d/1_SPIS3m1oue7XEYCdj2fCFJC9JQ9D37jNmETILRxuI0/export?format=pdf)
show_downloads: true